'use server';
// This is an autogenerated file from Firebase Studio.
/**
 * @fileOverview A Facebook ad copy generator AI agent.
 *
 * - generateAdCopy - A function that handles the ad copy generation process.
 * - GenerateAdCopyInput - The input type for the generateAdCopy function.
 * - GenerateAdCopyOutput - The return type for the generateAdCopy function.
 */

// NOTE: AI generation is temporarily disabled to resolve build issues. This file returns mock data.

import {z} from 'zod';

const GenerateAdCopyInputSchema = z.object({
  businessName: z.string().describe('The name of the business.'),
  industry: z.string().describe('The industry or niche of the business.'),
  targetAudience: z.string().describe('The target audience for the ad.'),
  offer: z.string().describe('The offer or lead magnet being promoted.'),
  websiteUrl: z.string().describe('The website URL to include in the ad.'),
});
export type GenerateAdCopyInput = z.infer<typeof GenerateAdCopyInputSchema>;

const GenerateAdCopyOutputSchema = z.object({
  adCopy: z.string().describe('The generated Facebook ad copy.'),
});
export type GenerateAdCopyOutput = z.infer<typeof GenerateAdCopyOutputSchema>;

export async function generateAdCopy(input: GenerateAdCopyInput): Promise<GenerateAdCopyOutput> {
  console.log("AI generation is mocked for ad copy. Returning static content.");
  
  await new Promise(resolve => setTimeout(resolve, 500));

  return {
    adCopy: `🚀 Supercharge your ${input.industry} business!\n\nThis is MOCK ad copy for ${input.businessName}. We're offering our exclusive '${input.offer}' for a limited time. Perfect for ${input.targetAudience}.\n\nVisit us at ${input.websiteUrl} to learn more!\n\n#${input.industry.replace(/\s/g, '')} #MockAd`,
  };
}
