'use server';
// This is an autogenerated file from Firebase Studio.
/**
 * @fileOverview A Facebook ad copy generator AI agent.
 *
 * - generateAdCopy - A function that handles the ad copy generation process.
 * - GenerateAdCopyInput - The input type for the generateAdCopy function.
 * - GenerateAdCopyOutput - The return type for the generateAdCopy function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateAdCopyInputSchema = z.object({
  businessName: z.string().describe('The name of the business.'),
  industry: z.string().describe('The industry or niche of the business.'),
  targetAudience: z.string().describe('The target audience for the ad.'),
  offer: z.string().describe('The offer or lead magnet being promoted.'),
  websiteUrl: z.string().describe('The website URL to include in the ad.'),
});
export type GenerateAdCopyInput = z.infer<typeof GenerateAdCopyInputSchema>;

const GenerateAdCopyOutputSchema = z.object({
  adCopy: z.string().describe('The generated Facebook ad copy.'),
});
export type GenerateAdCopyOutput = z.infer<typeof GenerateAdCopyOutputSchema>;

export async function generateAdCopy(input: GenerateAdCopyInput): Promise<GenerateAdCopyOutput> {
  return generateAdCopyFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateAdCopyPrompt',
  input: {schema: GenerateAdCopyInputSchema},
  output: {schema: GenerateAdCopyOutputSchema},
  prompt: `You are an expert marketing copywriter specializing in Facebook ads.

  Generate compelling ad copy based on the following business details:

  Business Name: {{{businessName}}}
  Industry: {{{industry}}}
  Target Audience: {{{targetAudience}}}
  Offer: {{{offer}}}
  Website URL: {{{websiteUrl}}}

  Ad Copy:`,
});

const generateAdCopyFlow = ai.defineFlow(
  {
    name: 'generateAdCopyFlow',
    inputSchema: GenerateAdCopyInputSchema,
    outputSchema: GenerateAdCopyOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
